-- 카테고리 별 최고 avg_ratio을 갖는 product_name
WITH RANKED_RESULT AS (
    SELECT CATEGORY, PRODUCT_NAME, ROUND(AVG(RATIO),1) AS AVERAGE_PRODUCTNAME_RATIO,
    ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY AVG(RATIO) DESC) AS RowNum
    FROM datatable 
    GROUP BY CATEGORY, PRODUCT_NAME 
)

SELECT CATEGORY, PRODUCT_NAME, AVERAGE_PRODUCTNAME_RATIO
FROM RANKED_RESULT
WHERE RowNum = 1 
ORDER BY 1,2 DESC